spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtSecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    security:
      jwt:
        secret-key: JsNVm2juYWzy78yatVOCZUnttbBxKjIuZmAuO/PMnaY+VM2nT6F8Z6N3MGaULriP
        expiration: 86400000
        refresh-token:
          expiration: 604800000 #7 days
      https:
        enabled: false
        redirect-http: true
        hsts-enabled: true
        hsts-max-age: 31536000 # 1 year

server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: springboot