spring:
  profiles:
    active: dev
  datasource:
    url: mysql://turntable.proxy.rlwy.net:31212/railway
    username: root
    password: EZwNMSHqMPITjtkmmNQgwDNxhSbBAyGk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    frontend-base-url: https://33bf19ba2d9e.ngrok-free.app
    security:
      jwt:
        expiration: 86400000
        refresh-token:
          expiration: 604800000 #7 days
        audience: pos-gateway-app
        issuer: pos-gateway
        password-reset:
          token-expiration-minutes: 30
          rate-limit-minutes: 1
      https:
        enabled: false
        redirect-http: true
        hsts-enabled: true
        hsts-max-age: 31536000 # 1 year
      lockout:
        max-failed-attempts: 5
        cooldown-minutes: 15
      session:
        max-concurrent-sessions: 3
        session-timeout-minutes: 30
        cleanup-interval-minutes: 5

server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: springboot