spring:
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/jwtSecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    security:
      jwt:
        secret-key: JsNVm2juYWzy78yatVOCZUnttbBxKjIuZmAuO/PMnaY+VM2nT6F8Z6N3MGaULriP
        expiration: 86400000
        refresh-token:
          expiration: 604800000 #7 days
        issuer: pos-gateway
        audience: pos-gateway-client
      enforce-https: false
      enable-2fa: true
      enable-logging: true
  logging:
    failed-logins: true
    successful-logins: true
    account-lockout: true
    rate-limit: true
    token-revocation: true
    suspicious-activity: true