spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST_E}:${MYSQLPORT_E}/${MYSQLDATABASE_E}
    username: ${MYSQLUSER_E}
    password: ${MYSQLPASSWORD_E}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
